// AUTO-GENERATED by firmware/node/gen_config.py from config/settings.yaml. Do not edit by hand.
#pragma once

// L0 physics limits on the device (section `physics`)
#define L0_TEMPERATURE_MIN_C -90.0f
#define L0_TEMPERATURE_MAX_C 60.0f
#define L0_PRESSURE_MIN_HPA 300.0f
#define L0_PRESSURE_MAX_HPA 1100.0f
#define L0_HUMIDITY_MIN_PCT 0.0f
#define L0_HUMIDITY_MAX_PCT 100.0f
#define L0_DEW_POINT_TOLERANCE_C 0.5f
#define L0_FROZEN_MINUTES 30

// Sampling and sending (section `node`)
#define SAMPLE_INTERVAL_MS 1000UL
#define AGGREGATE_SECONDS 60
#define MIN_VALID_SAMPLES 30
#define BUFFER_SLOTS 30
#define POST_TIMEOUT_MS 10000
