"""Writes firmware/node/config.h from config/settings.yaml, so the node uses the same limits as the server.

    python firmware/node/gen_config.py            # write config.h
    python firmware/node/gen_config.py --check    # exit 1 if config.h is out of date

Re-run it after changing `physics` or `node` in settings.yaml, then re-flash the node.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from atmos.config import load_settings  # noqa: E402

TARGET = Path(__file__).resolve().parent / "config.h"


def _f(x: float) -> str:
    return f"{float(x)!r}f"


def render(settings: dict) -> str:
    p, n = settings["physics"], settings["node"]
    r = p["ranges"]
    lines = [
        "// AUTO-GENERATED by firmware/node/gen_config.py from config/settings.yaml. Do not edit by hand.",
        "#pragma once",
        "",
        "// L0 physics limits on the device (section `physics`)",
        f"#define L0_TEMPERATURE_MIN_C {_f(r['temperature_c'][0])}",
        f"#define L0_TEMPERATURE_MAX_C {_f(r['temperature_c'][1])}",
        f"#define L0_PRESSURE_MIN_HPA {_f(r['pressure_hpa'][0])}",
        f"#define L0_PRESSURE_MAX_HPA {_f(r['pressure_hpa'][1])}",
        f"#define L0_HUMIDITY_MIN_PCT {_f(r['humidity_pct'][0])}",
        f"#define L0_HUMIDITY_MAX_PCT {_f(r['humidity_pct'][1])}",
        f"#define L0_DEW_POINT_TOLERANCE_C {_f(p['dew_point_tolerance_c'])}",
        f"#define L0_FROZEN_MINUTES {int(n['frozen_minutes'])}",
        "",
        "// Sampling and sending (section `node`)",
        f"#define SAMPLE_INTERVAL_MS {int(n['sample_interval_seconds']) * 1000}UL",
        f"#define AGGREGATE_SECONDS {int(n['aggregate_seconds'])}",
        f"#define MIN_VALID_SAMPLES {int(n['min_valid_samples'])}",
        f"#define BUFFER_SLOTS {int(n['buffer_slots'])}",
        f"#define POST_TIMEOUT_MS {int(n['post_timeout_seconds']) * 1000}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render(load_settings())
    if "--check" in argv:
        ok = TARGET.exists() and TARGET.read_text(encoding="utf-8") == text
        print("config.h is up to date" if ok else "config.h is OUT OF DATE: run gen_config.py")
        return 0 if ok else 1
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
